#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlet datatype/number
 

# << Many of the methods for calculating square roots of a positive real number
# S require an initial seed value. >>
#
# (http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Rough_estimation)
#
# We use sqrt(x) ~ 2^(d/2), where d is the number of binary digits of either x
# or 1/x, whatever happens to be greater.

#@method
function bashlets_math_function_rough_sqrt()
{
    awk -v x=${1:-0} -e '
        function rough_sqrt(x) {
            if (x > 1) {
                for (d = 0; x != 0; x = rshift(x, 1)) { d++ }
                d /= 2
                return lshift(0x1, d)
            } else if (x == 1) {
                return 1
            } else if (x > 0) {
                return rough_sqrt(1/x)
            } else {
                return -1
            }
        }

        BEGIN {
            print rough_sqrt(x)
            exit
        }
    '
}


#
# << Perhaps the first algorithm used for approximating sqrt(x) is known as the
#    "Babylonian method", named after the Babylonians, or "Heron's method", named
#    after the first-century Greek mathematician Hero of Alexandria who gave the
#    first explicit description of the method. >>
#
# (http://en.wikipedia.org/wiki/Methods_of_computing_square_roots#Babylonian_method)
#

#@method
function bashlets_math_function_sqrt()
{
    local x=${1:-1} tol=${2:-.000001}
    declare -i r

    $BASHLETS_NAMESPACE number validate_as_unsigned_float $x || {
        echo "input should be a valid number"
        return 1
    }

    # get a convenient approximation for the square root of x
    r=$(bashlets_math_function_rough_sqrt $x)

    awk -v x=$x -v r=$r -v tol=$tol -e "
         
        function abs(x) {
            return x >= -x ? x : -x
        }
         
        BEGIN {
            if (x < 1) {
                old_x = x
                x = 1 / x
            }

            # Heron's algorithm
            while (abs(old_r - r) >= tol) {
                old_r = r
                r = .5 * (r + x/r)
            }
         
            if (old_x) {
                r = 1 / r
            }

            # return result
            print r
        }
    "
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
