#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



# "integer" complex numbers
# inspired by http://rosettacode.org/wiki/Arithmetic/Complex#UNIX_Shell

#@method
function bashlets::math::icomplex::create()
{
	declare -i real="$1"
	declare -i img="$2"

	echo "$real:$img"
}

#@method
function bashlets::math::icomplex::to_real()
{
	declare w="$1"
	(
		IFS=":"
		set -- $w  # no quotes!
		echo "$1"
	)
}

#@method
function bashlets::math::icomplex::to_img()
{
	declare w="$1"
	(
		IFS=":"
		set -- $w  # no quotes!
		echo "$2"
	)
}

#@method
function bashlets::math::icomplex::to_s()
{
	declare w="$1"
	declare -i real img

	real="$(bashlets::math::icomplex::to_real "$w")"
	img="$(bashlets::math::icomplex::to_img "$w")"

	echo "$real + ${img}i"
}

#@method
function bashlets::math::icomplex::compare()
{
	declare w="$1" z="$2"
	declare -i w_real w_img z_real z_img

	w_real="$(bashlets::math::icomplex::to_real "$w")"
	w_img="$(bashlets::math::icomplex::to_img "$w")"
	z_real="$(bashlets::math::icomplex::to_real "$z")"
	z_img="$(bashlets::math::icomplex::to_img "$z")"

	[[ $w_real -eq $z_real && $w_img -eq $z_img ]]
}

#@method
function bashlets::math::icomplex::is_zero()
{
	declare w="$1"
	declare -i real img

	real="$(bashlets::math::icomplex::to_real "$w")"
	img="$(bashlets::math::icomplex::to_img "$w")"

	[[ "$real" -eq 0 && "$img" -eq 0 ]]
}

#@method
function bashlets::math::icomplex::negate()
{
	declare w="$1"
	declare -i real img

	real="$((-1 * $(bashlets::math::icomplex::to_real "$w")))"
	img="$((-1 * $(bashlets::math::icomplex::to_img "$w")))"

	bashlets::math::icomplex::create "$real" "$img"
}

#@method
function bashlets::math::icomplex::conjugate()
{
	declare w="$1"
	declare -i real img

	real="$(bashlets::math::icomplex::to_real "$w")"
	img="$((-1 * $(bashlets::math::icomplex::to_img "$w")))"

	bashlets::math::icomplex::create "$real" "$img"
}

#@method
function bashlets::math::icomplex::norm2()
{
	declare w="$1"
	declare -i real img

	real="$(bashlets::math::icomplex::to_real "$w")"
	img="$(bashlets::math::icomplex::to_img "$w")"

	echo "$((real**2 + img**2))"
}

#@method
function bashlets::math::icomplex::add()
{
	declare w="$1"
	declare z="$2"
	declare -i realw imgw
	declare -i realz imgz
	declare -i real img

	realw="$(bashlets::math::icomplex::to_real "$w")"
	realz="$(bashlets::math::icomplex::to_real "$z")"
	imgw="$(bashlets::math::icomplex::to_img "$w")"
	imgz="$(bashlets::math::icomplex::to_img "$z")"

	real="$((realw + realz))"
	img="$((imgw + imgz))"

	bashlets::math::icomplex::create "$real" "$img"
}

#@method
function bashlets::math::icomplex::subtract()
{
	declare w="$1"
	declare z="$2"

	bashlets::math::icomplex::add "$w" "$(bashlets_math_icomplex_negate "$z")"
}

#@method
function bashlets::math::icomplex::multiply()
{
	declare w="$1"
	declare z="$2"
	declare -i realw imgw
	declare -i realz imgz
	declare -i real img

	realw="$(bashlets::math::icomplex::to_real "$w")"
	realz="$(bashlets::math::icomplex::to_real "$z")"
	imgw="$(bashlets::math::icomplex::to_img "$w")"
	imgz="$(bashlets::math::icomplex::to_img "$z")"

	real=$((realw*realz - imgw*imgz))
	img=$((imgw*realz + realw*imgz))

	bashlets::math::icomplex::create "$real" "$img"
}

#@method
function bashlets::math::icomplex::square()
{
	declare w="$1"

	bashlets::math::icomplex::multiply "$w" "$w"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
