#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-6 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


#@method
function bashlets_datatype_char_ascii2decimal()
{
    ########################################################################
    #
    # cf. https://github.com/ldante86/tape/blob/master/tape.sh
    #
    # Copyright (C) 2015 Luciano D. Cecere <ldante86@aol.com>
    #
    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 2 of the License, or
    # (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
    #
    ########################################################################

    # TODO: add remaining values (e.g., lower case)

    declare -a CHARS=(
        \! \" \# $ % \& \' \( \) + \, - . /
        : \; \< = \> ? @ \` \{ \| \} \~
        \[ \\ \] \^ _
        {0..9} {A..Z}
    )

    # ASCII table that corresponds to CHARS
    declare -a DEC=(   
        33 34 35 36 37 38 39 40 41 43 44
        45 46 47 58 59 60 61 62 63 64
        96 123 124 125 126 91 92 93 94 95

        48 49 50 51 52 53 54 55 56 57

        65 66 67 68 69 70 71 72 73 74 75
        76 77 78 79 80 81 82 83 84 85 86
        87 88 89 90
    )

    local g

    for (( g=0; g<${#DEC[@]}; g++ ))
    do
        if [ "$1" = "${CHARS[g]}" ]; then
            echo ${DEC[g]}
            break
        fi
    done
}

#@method
function bashlets_datatype_char_decimal2ascii()
{
    ########################################################################
    #
    # cf. https://github.com/ldante86/tape/blob/master/tape.sh
    #
    # Copyright (C) 2015 Luciano D. Cecere <ldante86@aol.com>
    #
    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 2 of the License, or
    # (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
    #
    ########################################################################

    # TODO: add remaining values (e.g., lower case)

    declare -a CHARS=(
        \! \" \# $ % \& \' \( \) + \, - . /
        : \; \< = \> ? @ \` \{ \| \} \~
        \[ \\ \] \^ _
        {0..9} {A..Z}
    )

    # ASCII table that corresponds to CHARS
    declare -a DEC=(   
        33 34 35 36 37 38 39 40 41 43 44
        45 46 47 58 59 60 61 62 63 64
        96 123 124 125 126 91 92 93 94 95

        48 49 50 51 52 53 54 55 56 57

        65 66 67 68 69 70 71 72 73 74 75
        76 77 78 79 80 81 82 83 84 85 86
        87 88 89 90
    )

    local g

    for (( g=0; g<${#DEC[@]}; g++ ))
    do
        if [ "$1" = "${DEC[g]}" ]; then
            echo -n ${CHARS[g]}
            break
        fi
    done
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
