#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::datatype::byte
source bashlets core::datatype::unsigned
source bashlets core::datatype::integer
source bashlets core::datatype::float

#@public
function bashlets::core::datatype::number::new()
{
    :
}

#@public
function bashlets::core::datatype::number::destroy()
{
    :
}

#@public
function bashlets::core::datatype::number::to_string()
{
    echo "$@"
}

#@public
function bashlets::core::datatype::number::validate()
{
    $BASHLETS_NAMESPACE float validate "$@"
}

#@public
function bashlets::core::datatype::number::random()
{
    $BASHLETS_NAMESPACE float random
}

#@public
function bashlets::core::datatype::number::type()
{
    local input="$1"

    [[ -z $input ]] && return

    for type in byte unsigned integer float
    do
        if $BASHLETS_NAMESPACE $type validate "$input"
        then
            echo $type
            return
        fi
    done

    echo invalid
    return 1
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
