#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# Semantic versioning: https://semver.org/



#@public
function bashlets::datatype::semver::new()
{
    :
}

#@public
function bashlets::datatype::semver::destroy()
{
    :
}

#@public
function bashlets::datatype::semver::to_string()
{
    echo "$@"
}

#@public
function bashlets::datatype::semver::random()
{
    :
}

function __bashlets::datatype::semver::parse()
{
    # cf. https://github.com/cloudflare/semver_bash
    local semver="$1" group="${2:-0}"
    local regex='^([0-9]+)(\.([0-9]*))?(\.([0-9]*))?(([0-9A-Za-z-]*))?$'

    case $group in
        0)
            [[ $semver =~ $regex ]] && return 0 ;;
        [1-4])
            [[ $group -gt 0 ]] && group=$((1 + (group - 1) * 2))
            [[ $semver =~ $regex ]] || return 1
            echo "${BASH_REMATCH[$group]}"
            return 0 ;;
        *)
            return 1 ;;
    esac
}

#@public
function bashlets::datatype::semver::validate()
{
    __bashlets::datatype::semver::parse "$1"
}

#@public
function bashlets::datatype::semver::major()
{
    __bashlets::datatype::semver::parse "$1" 1
}

#@public
function bashlets::datatype::semver::minor()
{
    __bashlets::datatype::semver::parse "$1" 2
}

#@public
function bashlets::datatype::semver::patch()
{
    __bashlets::datatype::semver::parse "$1" 3
}

#@public
function bashlets::datatype::semver::special()
{
    __bashlets::datatype::semver::parse "$1" 4
}

function __bashlets::datatype::semver::sort()
{
    # naive Bash implementation
    # cf. http://stackoverflow.com/questions/16989598/
    test $# -gt 0 &&
        echo "$@"                                                     \
            | xargs -n 1                                              \
            | awk -F. '{ printf("%d.%d.%d.%s\n", $1, $2, $3, $0) }'   \
            | sort -t. -n -k1,3                                       \
            | sed 's/^[0-9]\.[0-9]\.[0-9]\.\([0-9]*\)/\1/'
}

#@public
function bashlets::datatype::semver::sort()
{
    (
        echo "$@" | xargs -n 1 | sort --version-sort

    ) 2> /dev/null || __bashlets::datatype::semver::sort "$@"
}

#@public
function bashlets::datatype::semver::lt()
{
    local min
    # GNU sort is needed here
    min="$(bashlets::datatype::semver::sort "$@" | head -1)"
    [[ $1 != $2 && $min == $1 ]]
}

#@public
function bashlets::datatype::semver::gt()
{
    local max
    # GNU sort is needed here
    max="$(bashlets::datatype::semver::sort "$@" | tail -1)"
    [[ $1 != $2 && $max == $1 ]]
}

#@public
function bashlets::datatype::semver::le()
{
    local min
    # GNU sort is needed here
    min="$(bashlets::datatype::semver::sort "$@" | head -1)"
    [[ $min == $1 ]]
}

#@public
function bashlets::datatype::semver::ge()
{
    local max
    # GNU sort is needed here
    max="$(bashlets::datatype::semver::sort "$@" | tail -1)"
    [[ $max == $1 ]]
}

#@public
function bashlets::datatype::semver::min()
{
    bashlets::datatype::semver::sort "$@" | head -1
}

#@public
function bashlets::datatype::semver::max()
{
    bashlets::datatype::semver::sort "$@" | tail -1
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
