#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-5 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlet charstream/reorder
source bashlet charstream/reshape

function bashlets_datatype_string_chop()
{
    echo "$(echo "$@" | tr -d "\n")"
}

function bashlets_datatype_string_length()
{
    local str="$*"
    echo ${#str}
}

function bashlets_datatype_string_upper()
{
    echo "$*" | tr [a-z] [A-Z]
}

function bashlets_datatype_string_lower()
{
    echo "$*" | tr [A-Z] [a-z]
}

function bashlets_datatype_string_to_charstream()
{
    local chr
    echo -n "$*" | while read -r -n1 chr; do echo "$chr"; done
}

function bashlets_datatype_string_transpose()
{
    bashlets_datatype_string_to_charstream "$*"
}

function bashlets_datatype_string_shuffle()
{
    local str="$*"

    [[ -n $str ]] || return

    bashlets_datatype_string_to_charstream "$str"    \
        | reorder shuffle                            \
        | reshape transpose
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
