#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets datatype/number
source bashlets os/random

#@public
function bashlets::datatype::unsigned::random()
{
    local size="${1:-16}"
    $BASHLETS_NAMESPACE random get "$size" 0-9
}

#@public
function bashlets::datatype::unsigned::validate()
{
    $BASHLETS_NAMESPACE number validate_as_unsigned "$1"
}

#@public
function bashlets::datatype::unsigned::is_even()
{
    $BASHLETS_NAMESPACE number validate_as_unsigned "$1" || return 1
    (($1 % 2 == 0))
}

#@public
function bashlets::datatype::unsigned::is_odd()
{
    $BASHLETS_NAMESPACE number validate_as_unsigned "$1" || return 1
    (($1 % 2 == 1))
}

#@public
function bashlets::datatype::unsigned::bin_to_dec()
{
    eval echo "$((2#$1))"
}

#@public
function bashlets::datatype::unsigned::bin_to_hex()
{
    printf "%x\n" $(bashlets::datatype::unsigned::bin_to_dec $1)
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
