#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets datatype/string
source bashlets os/random

#@public
function bashlets::datatype::unsigned::new()
{
    :
}

#@public
function bashlets::datatype::unsigned::destroy()
{
    :
}

#@public
function bashlets::datatype::unsigned::to_string()
{
    echo "$@"
}

#@public
function bashlets::datatype::unsigned::random()
{
    local size="${1:-16}"
    local raw="$($BASHLETS_NAMESPACE random get "$size" 0-9)"

    # avoid leading zeros, but printf "%d" has problems with arbitrary length
    raw="${raw##0}"
    [[ -z $raw ]] && raw=0

    echo "$raw"
}

#@public
function bashlets::datatype::unsigned::validate()
{
    [[ $1 =~ ^[0-9]+$ ]]
}

#@public
function bashlets::datatype::unsigned::is_even()
{
    (($1 % 2 == 0))
}

#@public
function bashlets::datatype::unsigned::is_odd()
{
    (($1 % 2 == 1))
}

#@public
function bashlets::datatype::unsigned::is_palindrome()
{
    local rev="$($BASHLETS_NAMESPACE string reverse "$1")"
    [[ $1 == $rev ]]
}

#@public
function bashlets::datatype::unsigned::select_bit()
{
    # cf. https://github.com/ldante86/punch/blob/master/punch.sh

    echo $(( $1 & (1<<$2) ))
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
