#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-6 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# cf. http://stackoverflow.com/questions/5991756/
# TODO parse internal output format!


source bashlet client/https

BASHLETS_API_OEIS_URL="https://oeis.org/"
BASHLETS_API_OEIS_PREFERRED_FORMAT=text  # text/json


#@method
function bashlets_api_oeis_validate_sequence_id()
{
    declare -u sequence_id="$1"
    [[ $sequence_id =~ ^A[0-9]{6}$ ]]
}

#@method
function bashlets_api_oeis_internal_get_name()
{
    while read line
    do
        [[ $line =~ ^%N[[:space:]]A[0-9]{6}[[:space:]](.*) ]]  \
            && echo ${BASH_REMATCH[1]} 
    done
}

#@method
function bashlets_api_oeis_get_sequence_by_id()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers
    local query

    bashlets_api_oeis_validate_sequence_id "$sequence_id"

    query="search?q=id:$sequence_id&fmt=$BASHLETS_API_OEIS_PREFERRED_FORMAT"
    $BASHLETS_NAMESPACE https get "$BASHLETS_API_OEIS_URL/$query"
}

#@method
function bashlets_api_oeis_describe_sequence_by_id()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers

    (
        # we need to use the internal format
        BASHLETS_API_OEIS_PREFERRED_FORMAT=text

        bashlets_api_oeis_get_sequence_by_id "$sequence_id"  \
            | bashlets_api_oeis_internal_get_name
    )
}

#@method
function bashlets_api_oeis_get_sequences_by_points()
{
    local points="$@"
    local query

    # cf. http://stackoverflow.com/questions/1527049/
    function join_by() { local IFS="$1"; shift; echo "$*"; }

    query="search?q=$(join_by , $@)&fmt=$BASHLETS_API_OEIS_PREFERRED_FORMAT"
    $BASHLETS_NAMESPACE https get "$BASHLETS_API_OEIS_URL/$query"

    unset join_by
}

#@method
function bashlets_api_oeis_describe_sequences_by_points()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers

    (
        # we need to use the internal format
        BASHLETS_API_OEIS_PREFERRED_FORMAT=text

        bashlets_api_oeis_get_sequences_by_points "$@"  \
            | bashlets_api_oeis_internal_get_name
    )
}

# grabs the images used to graph the data points

#@method
function bashlets_api_oeis_get_graph()
{
    declare -u sequence_id="${1:-A000040}"  # the prime numbers
    local query

    bashlets_api_oeis_validate_sequence_id "$sequence_id"

    query="$sequence_id/graph?png=1"
    $BASHLETS_NAMESPACE https get "$BASHLETS_API_OEIS_URL/$query"
}

#@method
function bashlets_api_oeis_get_recent()
{
    $BASHLETS_NAMESPACE https get "$BASHLETS_API_OEIS_URL/recent.txt"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
