#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-6 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# cf. https://www.twilio.com/docs/api/rest/sending-messages

#@method
function bashlets_api_twilio_send_sms()
{
    local to_number="$1" ; shift
    local msg="$@" response url

    # take only first 160 chars
    msg="${msg:0:160}"

    [[ -n $BASHLETS_API_TWILIO_ACCOUNTSID ]] || return 1
    [[ -n $BASHLETS_API_TWILIO_AUTHTOKEN  ]] || return 1
    [[ -n $BASHLETS_API_TWILIO_CALLERID   ]] || return 1

    url="https://api.twilio.com/2010-04-01/Accounts/$BASHLETS_API_TWILIO_ACCOUNTSID/Messages.json"

	# initiate a curl request to the Twilio REST API
    response="$(
        curl -fSs -X POST "$url"                                   \
            --data-urlencode "From=$BASHLETS_API_TWILIO_CALLERID"  \
            --data-urlencode "To=$to_number"                       \
            --data-urlencode "Body=$msg"                           \
            -u "$BASHLETS_API_TWILIO_ACCOUNTSID:$BASHLETS_API_TWILIO_AUTHTOKEN" 2>&1
    )"

	[ $? -gt 0 ] || return 1

	[[ -n $BASHLETS_API_TWILIO_VERBOSE ]] && echo "$response"
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
