#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-20 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::time::timestamp


#@public
function bashlets::core::time::year::new()
{
    :
}

#@public
function bashlets::core::time::year::destroy()
{
    :
}

#@public
function bashlets::core::time::year::to_string()
{
    echo "$@"
}

#@public
function bashlets::core::time::year::random()
{
    local timestamp="$($BASHLETS_NAMESPACE timestamp random)"
    date -d @"$timestamp" +%Y
}

#@public
function bashlets::core::time::year::validate()
{
    [[ $1 =~ ^[-+]?[0-9]{1,4}$ ]]
}

#@public
function bashlets::core::time::year::is_leap()
{
    # based on http://cfajohnson.com/shell/date-functions/?is_leap_year

    local year="$1"
    local gregorian=1752

    [[ -z $year ]] && printf -v year '%(%Y)T'

    if (( year > gregorian ))
    then
        case $year in
            *0[48]          |\
            *[2468][048]    |\
            *[13579][26]    |\
            *[02468][048]00 |\
            *[13579][26]00  )
                return 0 ;;
            *)
                return 1
        esac
    else
        (( year % 4 == 0 ))
    fi
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
