#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-5 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################



source bashlet marshal/uneval


function bashlets_revcontrol_svn_connect()
{
    uneval create
}

function bashlets_revcontrol_svn_disconnect()
{
    :
}

function bashlets_revcontrol_svn_get_param()
{
    local repo="$1"
    local key="$2"

    [[ -n $repo && -n $key ]] || return

    echo "$(uneval get_by_key "$repo" "$key")"
}

function bashlets_revcontrol_svn_set_param()
{
    local repo="$1"
    local key="$2"
    local value="$3"

    [[ -n $repo && -n $key ]] || return

    uneval add_pair "$repo" "$key" "$value"
}

function bashlets_revcontrol_svn_get_wd()
{
    local repo="$1"

    bashlets_revcontrol_svn_get_param "$repo" wd
}

function bashlets_revcontrol_svn_get_username()
{
    local repo="$1"

    bashlets_revcontrol_svn_get_param "$repo" username
}

function bashlets_revcontrol_svn_get_password()
{
    local repo="$1"

    bashlets_revcontrol_svn_get_param "$repo" password
}

function bashlets_revcontrol_svn_set_wd()
{
    local repo="$1"
    local wd="$2"

    bashlets_revcontrol_svn_set_param "$repo" wd "$wd"
}

function bashlets_revcontrol_svn_set_username()
{
    local repo="$1"
    local username="$2"

    bashlets_revcontrol_svn_set_param "$repo" username "$username"
}

function bashlets_revcontrol_svn_set_password()
{
    local repo="$1"
    local password="$2"

    bashlets_revcontrol_svn_set_param "$repo" password "$password"
}

function bashlets_revcontrol_svn_checkout()
{
    local repo="$1"
    local object="$2"
    local rev="${3:-HEAD}"

    local wd="$(bashlets_revcontrol_svn_get_wd "$repo")"
    local username="$(bashlets_revcontrol_svn_get_username "$repo")"
    local password="$(bashlets_revcontrol_svn_get_password "$repo")"

    [[ -n $object && -d $wd ]] || return 1

    (
        cd "$wd" || return 1

        command svn checkout                            \
            --quiet --non-interactive --no-auth-cache   \
            --revision "$rev"                           \
            --username "$username"                      \
            --password "$password"                      \
            "$object"
    )
}

function bashlets_revcontrol_svn_update()
{
    local repo="$1"
    local object="$2"
    local rev="${3:-HEAD}"

    local wd="$(bashlets_revcontrol_svn_get_wd "$repo")"
    local username="$(bashlets_revcontrol_svn_get_username "$repo")"
    local password="$(bashlets_revcontrol_svn_get_password "$repo")"

    [[ -n $object && -d $wd ]] || return 1

    (
        cd "$wd" || return 1

        command svn update                              \
            --quiet --non-interactive --no-auth-cache   \
            --revision "$rev"                           \
            --username "$username"                      \
            --password "$password"                      \
            "$object"
    )
}


function bashlets_revcontrol_svn_add()
{
    local repo="$1"
    local object="$2"

    local wd="$(bashlets_revcontrol_svn_get_wd "$repo")"
    local username="$(bashlets_revcontrol_svn_get_username "$repo")"
    local password="$(bashlets_revcontrol_svn_get_password "$repo")"

    [[ -n $object && -d $wd ]] || return 1

    (
        cd "$wd" || return 1

        command svn add                                 \
            --quiet --non-interactive --no-auth-cache   \
            --username "$username"                      \
            --password "$password"                      \
            "$object"
    )
}

function bashlets_revcontrol_svn_commit()
{
    local repo="$1"
    local object="$2"
    shift 2

    local wd="$(bashlets_revcontrol_svn_get_wd "$repo")"
    local username="$(bashlets_revcontrol_svn_get_username "$repo")"
    local password="$(bashlets_revcontrol_svn_get_password "$repo")"

    [[ -n $object && -d $wd ]] || return 1

    (
        cd "$wd" || return 1

        command svn commit                              \
            --quiet --non-interactive --no-auth-cache   \
            --username "$username"                      \
            --password "$password"                      \
            --message  "$@"
            "$object"
    )
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
