#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


#@public
function bashlets::core::github::api::get()
{
    local url="$1"

    [[ -n $url ]] || return

    if [[ -n $BASHLETS_GITHUB_OAUTH_TOKEN ]]
    then
        curl -s                                                    \
            -H "Authorization: token $BASHLETS_GITHUB_OAUTH_TOKEN" \
            "$url"
    else
        curl -s                                                    \
            "$url"
    fi
}

#@public
function bashlets::core::github::api::header()
{
    local url="$1" key="${2:-[^:]\+}"

    [[ -n $url ]] || return

    if [[ -n $BASHLETS_GITHUB_OAUTH_TOKEN ]]
    then
        curl -sI                                                   \
            -H "Authorization: token $BASHLETS_GITHUB_OAUTH_TOKEN" \
            "$url" | grep "^$key: "
    else
        curl -sI                                                   \
            "$url" | grep "^$key: "
    fi
}

#@public
function bashlets::core::github::api::header_value()
{
    local url="$1" key="${2:-[^:]\+}"

    [[ -n $url ]] || return

    if [[ -n $BASHLETS_GITHUB_OAUTH_TOKEN ]]
    then
        curl -sI                                                   \
            -H "Authorization: token $BASHLETS_GITHUB_OAUTH_TOKEN" \
            "$url" | sed -n "s/^$key: \(.*\)/\\1/p"
    else
        curl -sI                                                   \
            "$url" | sed -n "s/^$key: \(.*\)/\\1/p"
    fi
}

#@public
function bashlets::core::github::api::post()
{
    local url="$1" data="${2:-\{\}}"

    [[ -n $url || -n $BASHLETS_GITHUB_OAUTH_TOKEN ]] || return

    curl -s -X POST                                            \
        -H "Content-Type: application/json"                    \
        --data "$data"                                         \
        -H "Authorization: token $BASHLETS_GITHUB_OAUTH_TOKEN" \
        "$url"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
