#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::github::api

# Get properties of an individual code of conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#get-an-individual-code-of-conduct
function __bashlets::core::github::conduct::value()
{
    local key="${1:-contributor_covenant}" field="${2:-key}"
    local url="/codes_of_conduct/$key"
    
    (
        # The Codes of Conduct API is currently available for developers to
        # preview. To access the API during the preview period, we must provide
        # a custom media type in the Accept header.
        #
        # @cf https://developer.github.com/v3/codes_of_conduct/#codes-of-conduct

        BASHLETS_CORE_GITHUB_API_CUSTOM_HEADERS="$BASHLETS_CORE_GITHUB_API_CUSTOM_HEADERS -H 'Accept: application/vnd.github.scarlet-witch-preview+json'"
        $BASHLETS_NAMESPACE api get "$url" ".\"$field\""
    )
}

# Get the name of an individual code of conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#get-an-individual-code-of-conduct
# @public
function bashlets::core::github::conduct::name()
{
    local key="${1:-contributor_covenant}"
    __bashlets::core::github::conduct::value "$key" name
}

# Get the url of an individual code of conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#get-an-individual-code-of-conduct
# @public
function bashlets::core::github::conduct::url()
{
    local key="${1:-contributor_covenant}"
    __bashlets::core::github::conduct::value "$key" url
}

# Get the text of an individual code of conduct.
#
# @cf   https://developer.github.com/v3/codes_of_conduct/#get-an-individual-code-of-conduct
# @public
function bashlets::core::github::conduct::text()
{
    local key="${1:-contributor_covenant}"
    __bashlets::core::github::conduct::value "$key" body
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
