#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core/os/random


#@public
function bashlets::core::datatype::float::new()
{
    :
}

#@public
function bashlets::core::datatype::float::destroy()
{
    :
}

#@public
function bashlets::core::datatype::float::to_string()
{
    echo "$@"
}

#@public
function bashlets::core::datatype::float::random()
{
    local size="${1:-16}" scale="${2:-12}"
    local raw x y sign output

    raw="$($BASHLETS_NAMESPACE random get $((size+scale)) 0-9)"

    # avoid leading zeros, but printf "%d" has problems with arbitrary length
    raw="${raw##0}"

    x="${raw:0:$size}"
    y="${raw:$size:$scale}"

    sign="$($BASHLETS_NAMESPACE random get 1 +-)"
    [[ $sign == + ]] && sign=

    # simplify output
    if [[ $x -eq 0 ]]
    then
        if [[ $scale -eq 0 ]]
        then
            # prefer 0 over -0
            sign=
        else
            # prefer .123... over 0.123...
            x=
        fi
    fi

    output="${sign}${x}"
    [[ -n $y ]] && output="${output}.${y}"

    echo "$output"
}

#@public
function bashlets::core::datatype::float::validate()
{
    [[ $1 =~ ^[-+]?[0-9]*\.?[0-9]+$ ]]
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
