#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::github::api

# Create a gist.
#
# @cf   https://developer.github.com/v3/gists/#create-a-gist
# @public
function bashlets::core::github::gist::create()
{
    local id="${1:?Gist id required}"

    $BASHLETS_NAMESPACE api create "/gists/$id"
}

# Delete a gist.
#
# @cf   https://developer.github.com/v3/gists/#delete-a-gist
# @public
function bashlets::core::github::gist::delete()
{
    local id="${1:?Gist id required}"

    $BASHLETS_NAMESPACE api delete "/gists/$id"
}

# Check if a gist is starred.
#
# @cf   https://developer.github.com/v3/gists/#check-if-a-gist-is-starred
# @public
function bashlets::core::github::gist::is_starred()
{
    local id="${1:?Gist id required}"
    local url="/gists/$id/star"
    local status

    status="$($BASHLETS_NAMESPACE api status "$url")"

    [[ $status == 204 ]]
}

# Star a gist.
#
# @cf   https://developer.github.com/v3/gists/#star-a-gist
# @public
function bashlets::core::github::gist::star()
{
    local id="${1:?Gist id required}"

    $BASHLETS_NAMESPACE api put "/gists/$id/star"
}

# Unstar a gist.
#
# @cf   https://developer.github.com/v3/gists/#unstar-a-gist
# @public
function bashlets::core::github::gist::unstar()
{
    local id="${1:?Gist id required}"

    $BASHLETS_NAMESPACE api delete "/gists/$id/star"
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
