#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core/datatype/integer
source bashlets core/datatype/unsigned


#@public
function bashlets::core::math::integer::abs()
{
    local value="$1"
    local opposite
    $BASHLETS_NAMESPACE integer validate "$value" || return 1
    opposite="$((-1*value))"
    [[ $value -ge $opposite ]] && echo "$value" || echo "$opposite"
}

#@public
function bashlets::core::math::integer::sign()
{
    local value="$1"
    local opposite
    $BASHLETS_NAMESPACE integer validate "$value" || return 1
    [[ $value -eq 0 ]] && { echo 0 ; return ; }
    opposite="$((-1*value))"
    [[ $value -ge $opposite ]] && echo 1 || echo -1
}

#@public
function bashlets::core::math::integer::get_unique_factors()
{
    local pass_0

    $BASHLETS_NAMESPACE integer validate "$value" || return 1

    declare -i n="$1"
    declare -i sign=1

    # is $n < 0?
    test $n -lt 0 && {
        sign=-1
        n=$((-1*n))
    }

    # call factor(1)
    pass_0="$(factor $n 2> /dev/null)" || return 1

    # is $n == 0?
    # then the call to factor(1) above just returned the string "0:"
    test $n -eq 0 && pass_0="$pass_0 0"

    echo "$pass_0" | cut -d: -f2 | (
        test $sign -lt 0 && echo -1
        cat
    ) | xargs -n 1 echo | uniq -c
}


#
# fast modular exponentiation
#
#   see http://en.wikipedia.org/wiki/Modular_exponentiation
#

#@public
function bashlets::core::math::integer::modular_pow()
{
    local base=$1 expon=$2 mod=$3

    $BASHLETS_NAMESPACE integer  validate $base  || return 1
    $BASHLETS_NAMESPACE integer  validate $expon || return 1
    $BASHLETS_NAMESPACE unsigned validate $mod   || return 1

    ((mod > 0)) || return 1

    awk -v base=$base -v expon=$expon -v mod=$mod -e '
        function modular_pow(base, expon, mod) {
            result = 1

            while (expon > 0) {
                if (and(expon, 1) == 1) {
                    result = (result * base) % mod
                }

                expon = rshift(expon, 1)
                base = (base * base) % mod
            }

            return result
        }

        BEGIN {
            print modular_pow(base, expon, mod)
            exit
        }
    '
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
