#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::github::api
source bashlets core::github::json
source bashlets core::github::page

# Add email address(es).
#
# @cf   https://developer.github.com/v3/users/emails/#add-email-addresses
# @public
function bashlets::core::github::my::add_emails()
{
    local url="/user/emails"
    local data

    [[ $# -gt 0 ]] || return

    data="$($BASHLETS_NAMESPACE json build_array "$@")"

    $BASHLETS_NAMESPACE api post "$url" "$data" length
}

# Delete email address(es).
#
# @cf   https://developer.github.com/v3/users/emails/#delete-email-addresses
# @public
function bashlets::core::github::my::delete_emails()
{
    local url="/user/emails"
    local data

    [[ $# -gt 0 ]] || return

    data="$($BASHLETS_NAMESPACE json build_array "$@")"

    $BASHLETS_NAMESPACE api delete "$url" "$data"
}

# List email addresses for the authenticated user.
#
# @cf   https://developer.github.com/v3/users/emails/#list-email-addresses-for-a-user
# @public
function bashlets::core::github::my::emails()
{
    local limit="${1:-100}" callback="${2:-cat}"
    local url="/user/emails"

    $BASHLETS_NAMESPACE page items "$url" email "$limit" "$callback"
}

# List followers of the authenticated user.
#
# @cf   https://developer.github.com/v3/users/followers/#list-followers-of-a-user
# @public
function bashlets::core::github::my::followers()
{
    local since="${1:-0}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/user/followers?since=$since"

    $BASHLETS_NAMESPACE page items "$url" login "$limit" "$callback"
}

# List all the organizations for the authenticated user.
#
# @cf   https://developer.github.com/v3/orgs/#list-your-organizations
# @public
function bashlets::core::github::my::orgs()
{
    local limit="${1:-100}" callback="${2:-cat}"
    local url="/user/orgs"

    $BASHLETS_NAMESPACE page items "$url" login "$limit" "$callback"
}

# List public email addresses for the authenticated user.
#
# @cf   https://developer.github.com/v3/users/emails/#list-public-email-addresses-for-a-user
# @public
function bashlets::core::github::my::public_emails()
{
    local limit="${1:-100}" callback="${2:-cat}"
    local url="/user/public_emails"

    $BASHLETS_NAMESPACE page items "$url" email "$limit" "$callback"
}

# List all the repositories for the authenticated user.
#
# @cf   https://developer.github.com/v3/repos/#list-your-repositories
# @public
function bashlets::core::github::my::repos()
{
    local limit="${1:-100}" callback="${2:-cat}"
    local url="/user/repos"

    $BASHLETS_NAMESPACE page items "$url" name "$limit" "$callback"
}

# Toggle primary email visibility.
#
# @cf   https://developer.github.com/v3/users/emails/#toggle-primary-email-visibility
# @public
function bashlets::core::github::my::toggle_primary_email_visibility()
{
    local url="/user/email/visibility"

    $BASHLETS_NAMESPACE api patch "$url" "" .[].visibility
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
