#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::github::api

# Get the current rate limit status.
#
# @cf   https://developer.github.com/v3/rate_limit/#get-your-current-rate-limit-status
# @public
function bashlets::core::github::rate_limit::limit()
{
    local resource="${1:-core}"  # core/search
    local url="/rate_limit"

    $BASHLETS_NAMESPACE api get "$url" .resources."$resource".limit
}

# Get the current rate limit status.
#
# @cf   https://developer.github.com/v3/rate_limit/#get-your-current-rate-limit-status
# @public
function bashlets::core::github::rate_limit::remaining()
{
    local resource="${1:-core}"  # core/search
    local url="/rate_limit"

    $BASHLETS_NAMESPACE api get "$url" .resources."$resource".remaining
}

# Get the current rate limit status.
#
# @cf   https://developer.github.com/v3/rate_limit/#get-your-current-rate-limit-status
# @public
function bashlets::core::github::rate_limit::reset()
{
    local resource="${1:-core}"  # core/search
    local url="/rate_limit"

    $BASHLETS_NAMESPACE api get "$url" .resources."$resource".reset
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
