#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlets core::github::defs
source bashlets core::github::page

# @cf   https://developer.github.com/v3/gists/#list-a-users-gists
#@public
function bashlets::core::github::user::gists()
{
    local user="${1:-bashlets}"
    local since="${2:-$BASHLETS_CORE_GITHUB_API_EPOCH}"
    local limit="${3:-100}" callback="${4:-cat}"
    local url="/users/$user/gists?since=$since"

    $BASHLETS_NAMESPACE page items "$url" id "$limit" "$callback"
}

# List public repositories for the specified user.
#
# @cf   https://developer.github.com/v3/repos/#list-user-repositories
#@public
function bashlets::core::github::user::repos()
{
    local user="${1:-bashlets}"
    local type="${2:-owner}"      # all/owner/member
    local sort="${3:-full_name}"  # created/updated/pushed/full_name
    local direction="${4:-asc}"   # asc/desc
    local limit="${5:-100}" callback="${6:-cat}"

    local url="/users/$user/repos?type=$type&sort=$sort&direction=$direction"

    $BASHLETS_NAMESPACE page items "$url" name "$limit" "$callback"
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
