#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-6 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlet charstream/strip

BASHLETS_API_CHOOSEALICENSE_URL="http://choosealicense.com/licenses/"


#@method
function bashlets_api_choosealicense_get_license()
{
    local   license="${1:-gpl-3.0}"

    curl -s "$BASHLETS_API_CHOOSEALICENSE_URL/$license/"  \
        | sed -n '/<pre id="license-text">/,/<\/pre>/p'   \
        | strip leading_spaces                            \
        | strip html_tags
}

#@method
function bashlets_api_choosealicense_list_licenses()
{
    echo mit           # MIT License
    echo apache-2.0    # Apache License 2.0
    echo gpl-3.0       # GNU General Public License v3.0

    echo agpl-3.0      # GNU Affero General Public License v3.0
    echo lgpl-3.0      # GNU General Public License v3.0
    echo mpl-2.0       # Mozilla Public License 2.0

    # Non-Software Licenses
    echo cc0-1.0       # Creative Commons Zero v1.0 Universal
    echo cc-by-4.0     # Creative Commons Attribution 4.0
    echo cc-by-sa-4.0  # Creative Commons Attribution Share Alike 4.0

    # Fonts
    echo ofl-1.1       # SIL Open Font License 1.1

    echo unlicense     # The Unlicense
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
