#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-5 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlet datatype/char

#@method
function bashlets_charstream_convert_dos2unix()
{
    local input="$1"
    local output="$2"

    type dos2unix > /dev/null 2>&1 && {
        function dos2unix() { command dos2unix ; }
    } || {
        function dos2unix() { tr -d "\r" ; }
    }
    
    (test -n "$input" && cat "$input" || cat) |  \
        dos2unix | (test -n "$output" && cat > "$output" || cat)

    unset dos2unix
}

#@method
function bashlets_charstream_convert_unix2dos()
{
    local input="$1"
    local output="$2"

    type unix2dos > /dev/null 2>&1 && {
        function unix2dos() { command unix2dos ; }
    } || {
        function unix2dos() { sed "s/$/\r/" ; }
    }
    
    (test -n "$input" && cat "$input" || cat) |  \
        unix2dos | (test -n "$output" && cat > "$output" || cat)

    unset unix2dos
}

function __bashlets_charstream_convert_punch()
{
    ########################################################################
    #
    # punch - Convert text to punch cards
    # cf. https://github.com/ldante86/punch/blob/master/punch.sh
    #
    # Copyright (C) 2015 Luciano D. Cecere <ldante86@aol.com>
    #
    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 2 of the License, or
    # (at your option) any later version.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.
    #
    ########################################################################

    declare -u str="$@"

    local COLUMNS=48


    declare -a ROWCHARS=(" " " " " " 1 2 3 4 5 6 7 8 9)

    declare -a HOLES=(
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 518
        522 66 1090 546 2048 1030 2066 1042 1058 2560 578 1024 2114 768 512 256
        128 64 32 16 8 4 2 1 18 1034 2058 530 10 6 34 2304 2176 2112 2080 2064
        2056 2052 2050 2049 1280 1152 1088 1056 1040 1032 1028 1026 1025 640
        576 544 528 520 516 514 513 130 2082 1536 642 783 2304 2176 2112 2080
        2064 2056 2052 2050 2049 1280 1152 1088 1056 1040 1032 1028 1026 1025
        640 576 544 528 520 516 514 513 130 2054 2082 1536 642 0 0 0 0 0 0 0 0
        0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 518 522 66 1090 546
        2048 1030 2066 1042 1058 2560 578 1024 2114 768 512 256 128 64 32 16 8
        4 2 1 18 1034 2058 530 10 6 34 2304 2176 2112 2080 2064 2056 2052 2050
        2049 1280 1152 1088 1056 1040 1032 1028 1026 1025 640 576 544 528 520
        516 514 513 130 2054 2082 1536 642 783 2304 2176 2112 2080 2064 2056
        2052 2050 2049 1280 1152 1088 1056 1040 1032 1028 1026 1025 640 576 544
        528 520 516 514 513 130 2054 2082 1536 642 0
    )

    function _bit()
    {
        echo $(( $1 & (1<<$2) ))
    }

    if [ ${#str} -gt $COLUMNS ]; then
        str=${str:0:COLUMNS}
    fi

    echo -n " "
    for ((i=0; i<=$COLUMNS; i++))
    do
        echo -n "_"
    done
    echo

    echo -n "/"
    for ((i=0; i<${#str}; i++))
    do
        p=$(char ascii2decimal ${str:i:1})
        if [ ${HOLES[p]} ]; then
            echo -n "${str:i:1}"
        else
            echo -n " "
        fi
    done

    while [ $((i++)) -lt $COLUMNS ]
    do
        echo -n " "
    done
    echo "|"

    for ((row=0; row<=11; row++))
    do
        echo -n "|"
        for ((i=0; i<${#str}; i++))
        do
            p=$(char ascii2decimal ${str:i:1})
            if [ $(_bit ${HOLES[p]} $((11 - row)) ) -ne 0 ]; then
                echo -n "]"
            else
                echo -n "${ROWCHARS[row]}"
            fi
        done
        while [ $((i++)) -lt $COLUMNS ]
        do
            echo -n "${ROWCHARS[row]}"
        done
        echo "|"
    done

    for ((i=0; i<=$COLUMNS; i++))
    do
        echo -n "_"
    done
    echo "|"

    unset _bit
}

#@method
function bashlets_charstream_convert_punch()
{
    while read
    do
        __bashlets_charstream_convert_punch "$REPLY"
    done
}

################################ EOF ###################################
# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
