#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-8 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


#@method
function bashlets_os_fs_dir_is_empty()
{
    local dir="$1"
    # cf. http://superuser.com/questions/352289/

    test -d "$dir" || return 2

    # shellcheck disable=SC2065
    2> /dev/null test -e "$1/"*

    case $? in
        1)   return 0 ;;
        *)   return 1 ;;
    esac
}


#@method
function bashlets_os_fs_walk()
{
    local base="$1"
    local callback="${2:-__bashlets_os_fs_walk_echo}"

    function __bashlets_os_fs_walk_echo()
    {
        echo "$@"
    }

    function __bashlets_os_fs_walk()
    {
        local name

        bashlets_os_fs_dir_is_empty "$(pwd)" && return

        for name in *
        do
            $callback "$name"
            test -d "$name" && {
                cd "$name" || continue  # skip on permission denied
                __bashlets_os_fs_walk
                cd ..
            }
        done
    }

    (
        shopt -s dotglob  # include hidden files

        cd "$base"
        __bashlets_os_fs_walk
    )

    unset __bashlets_os_fs_walk
    unset __bashlets_os_fs_walk_echo
}


# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
