#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-6 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


source bashlet datatype/string
source bashlet oracle/sqlplus


#@method
function bashlets_oracle_database_get_instance_name()
{
	local query
    
    query="SELECT SYS_CONTEXT('userenv', 'instance_name') FROM dual"

	$BASHLETS_NAMESPACE string chop "$(
        $BASHLETS_NAMESPACE sqlplus execute "$query"
    )"
}

#@method
function bashlets_oracle_database_get_instance_number()
{
    local query instance_name

	instance_name="$(bashlets_oracle_database_get_instance_name)"

	query="
        SELECT     instance_number
            FROM   gv\$instance
            WHERE UPPER(instance_name) = UPPER('$instance_name')
    "

	$BASHLETS_NAMESPACE string chop "$(
        $BASHLETS_NAMESPACE sqlplus execute "$query"
    )"
}

#@method
function bashlets_oracle_database_get_dbid()
{
    local query
    
    query="SELECT DISTINCT dbid FROM v\$database"
	echo $($BASHLETS_NAMESPACE sqlplus execute "$query" | tr -d "\n")
}

#@method
function bashlets_oracle_database_is_primary()
{
    local query role
    
    query="SELECT database_role FROM v\$database"
	role="$($BASHLETS_NAMESPACE sqlplus execute "$query" | tr -d "\n")"
    [[ "$role" == "PRIMARY" ]]
}

#@method
function bashlets_oracle_database_is_physical_standby()
{
    local query role
    
    query="SELECT database_role FROM v\$database"
	role="$($BASHLETS_NAMESPACE sqlplus execute "$query" | tr -d "\n")"
    [[ "$role" == "PHYSICAL STANDBY" ]]
}

#@method
function bashlets_oracle_database_is_logical_standby()
{
    local query role
    
    query="SELECT database_role FROM v\$database"
	role="$($BASHLETS_NAMESPACE sqlplus execute "$query" | tr -d "\n")"
    [[ "$role" == "LOGICAL STANDBY" ]]
}

#@method
function bashlets_oracle_database_is_standby()
{
       bashlets_oracle_database_is_physical_standby  \
    || bashlets_oracle_database_is_logical_standby
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
