#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2014-5 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


#@method
function bashlets_oracle_sqlplus_execute()
{
    local timezone
    local cmd
    local funcname="$FUNCNAME"

    function bashlets_oracle_sqlplus_execute_usage()
    {
        echo "Usage: $funcname [-z <timezone>]"
    }

    [[ -z "$ORACLE_HOME" || -z "$ORACLE_SID" ]] && {
        echo "Oracle environment variables undefined!"
        return 1
    }

    local OPTIND opt
    while getopts ":z:" opt
    do
        case "$opt" in
            z)
                timezone="${OPTARG}"
                ;;
            *)
                bashlets_oracle_sqlplus_execute_usage # && return 2
                ;;
        esac
    done
    shift $((OPTIND-1))

    # prepare header
    cmd="
        CONNECT / AS SYSDBA
        SET FEEDBACK OFF
        SET HEADING OFF
        SET SERVEROUTPUT ON
        SET VERIFY OFF
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        WHENEVER OSERROR EXIT"

    # set timezone if required
    [[ -n $timezone ]] && cmd="$cmd
        ALTER SESSION SET TIME_ZONE='$timezone';"

    # add actual query and finalise command
    cmd="$cmd
        $@;
        EXIT"

    echo "$cmd" | "$ORACLE_HOME/bin/sqlplus" -s /nolog
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
