#!/bin/bash


################################################################################
#                                         
# |              |    |         |         
# |---.,---.,---.|---.|    ,---.|--- ,---.
# |   |,---|`---.|   ||    |---'|    `---.
# `---'`---^`---'`   '`---'`---'`---'`---'
#
#                                        
# Bashlets -- A modular extensible toolbox for Bash
#
# Copyright (c) 2016 Roberto Reale
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################


# environment variables
#
#   ORACLE_HOME
#   BASHLETS_ORACLE_WLST_DOMAINNAME
#   BASHLETS_ORACLE_WLST_SERVERNAME
#   BASHLETS_ORACLE_WLST_USERNAME
#   BASHLETS_ORACLE_WLST_PASSWORD
#   BASHLETS_ORACLE_WLST_HOST
#   BASHLETS_ORACLE_WLST_PORT

function __bashlets_oracle_wlst_wrapper()
{
    $ORACLE_HOME/oracle_common/common/bin/wlst.sh <<- ???
 
        nmConnect(
            domainName='$BASHLETS_ORACLE_WLST_DOMAINNAME', 
            username='$BASHLETS_ORACLE_WLST_USERNAME',
            password='$BASHLETS_ORACLE_WLST_PASSWORD',
            host='$BASHLETS_ORACLE_WLST_HOST',
            port='$BASHLETS_ORACLE_WLST_PORT'
        )
         
        nmServerStatus(
            serverName='$BASHLETS_ORACLE_WLST_SERVERNAME',
            serverType='OHS'
        )
	???
}

#@method
function bashlets_oracle_wlst_ohs_is_running()
{
    __bashlets_oracle_wlst_wrapper | grep ^RUNNING$ > /dev/null
}

# Local variables:
# mode: shell-script
# sh-basic-offset: 4
# sh-indent-comment: t
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et filetype=sh
